import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import NavBar from "./NavBar";
import SessionProvider from "./auth/Provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-html="winter" lang="en">
      <body className={inter.variable}>
        <SessionProvider>
          <NavBar></NavBar>
          <main className="p-5 text-blue-500">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
